fix: convert to bool problem
ClusterReader.cpp:70:24: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in initialization
   70 |     bool good = getline(*m_pReader, line);
      |                 ~~~~~~~^~~~~~~~~~~~~~~~~~
      |                        |
      |                        std::basic_istream<char>